plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme  

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/Los_Angeles

url: https://ucsb-cs64.github.io 
baseurl: "/"  
github_url: https://github.com/ucsb-cs64/ucsb-cs64.github.io

title: "UCSB CS64"
course: "CS64"